# Python : Data Science Foundation

## Numpy

In [21]:
# to calculate time for an array of speed and distance
distance =[50,100,78,986]
speed=[45,120,76,80]
#converting list into an array
import numpy as np

dist = np.array(distance)
spd = np.array(speed)
time = dist/spd
print(dist)
print(spd)
print(time)

[ 50 100  78 986]
[ 45 120  76  80]
[ 1.11111111  0.83333333  1.02631579 12.325     ]


In [36]:
#arange: works as a sequence in increment of 1
num = np.arange(10)
#arange: works as a sequence in increment of 5 between 50 to 100
num1 = np.arange(50,100,5)
#linspace: creates an evenly spaced numbers within a fixed intervals
num2= np.linspace(8,12,7)

In [38]:
print(num)
print(num1)
print(num2)

[0 1 2 3 4 5 6 7 8 9]
[50 55 60 65 70 75 80 85 90 95]
[ 8.          8.66666667  9.33333333 10.         10.66666667 11.33333333
 12.        ]


In [39]:
#reshaping Data
data = np.array((32,45,123,756,23,2123,1,2,3,4,5,6,6,5,4,3,2,1,78,89,87,76,54,31))
data.shape

(24,)

In [40]:
data.reshape(6,4)

array([[  32,   45,  123,  756],
       [  23, 2123,    1,    2],
       [   3,    4,    5,    6],
       [   6,    5,    4,    3],
       [   2,    1,   78,   89],
       [  87,   76,   54,   31]])

In [46]:
# creating 2d arrays with 0 numbered
np.zeros((3,5))
# creating 2d arrays with 1 numbered
np.ones((3,5))
#populating the diagonal elements only
np.diag(([23,44,21,42,24,88]))
#creating 4*4 identity matrix
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Pandas

In [2]:
import pandas as pd

#creating a series
series_1 = pd.Series([22,45,39,88])
series_1

0    22
1    45
2    39
3    88
dtype: int64

In [49]:
# specifying index values
series_2 = pd.Series([22,45,39,88], index =["A","B","C","D"])
series_2

A    22
B    45
C    39
D    88
dtype: int64

In [50]:
# adding 5 to every element
series_2 +5

A    27
B    50
C    44
D    93
dtype: int64

In [51]:
#cubing every element
series_2 **3

A     10648
B     91125
C     59319
D    681472
dtype: int64

In [52]:
#filtering a series
series_2[series_2>30]

B    45
C    39
D    88
dtype: int64

### creating a series data structure from a dictionary

In [4]:
#calculating the EPS values of a firm

years=[81,82,83,84,85,86,87,88,89]
f1 ={87:4,84:8,81:23,83:33,82:12,85:55,86:3,88:23,89:44}
firm1 =pd.Series(f1, index = years)
firm1

81    23
82    12
83    33
84     8
85    55
86     3
87     4
88    23
89    44
dtype: int64

### DATAFRAME

#### DataFrame is a tabular data structure in which data is laid out in rows and column format, but it can also be used for higher dimensional data sets.

In [6]:
#creating a dataframe

data = pd.DataFrame({
    "Name":["Yash","Raj","Krish"],
    "Age":[65,76,35],
    "Country":["USA","LONDON","INDIA"]
})

In [7]:
data

Name  Age Country
0   Yash   65     USA
1    Raj   76  LONDON
2  Krish   35   INDIA

In [17]:
# add additional column of "Sex"

data["Sex"] = "male"

In [18]:
data

Name  Age Country   Sex
0   Yash   65     USA  male
1    Raj   76  LONDON  male
2  Krish   35   INDIA  male

In [19]:
#deleting age column
del data["Age"]
data

Name Country   Sex
0   Yash     USA  male
1    Raj  LONDON  male
2  Krish   INDIA  male

In [23]:
# creating a networth column with NaN values

data["Net-Worth"] = np.NaN
data

Name Country   Sex  Net-Worth
0   Yash     USA  male        NaN
1    Raj  LONDON  male        NaN
2  Krish   INDIA  male        NaN

### Using Numpy function inside a DataFrame object

In [26]:
dataframe = pd.DataFrame(np.random.randn(3,3),columns =["One","Two","Three"])

In [27]:
dataframe

One       Two     Three
0  0.993189  0.814437 -0.680529
1 -0.643883 -0.921863  0.702137
2 -0.233943 -1.074849  0.143718

In [28]:
#absolute values

np.abs(dataframe)

One       Two     Three
0  0.993189  0.814437  0.680529
1  0.643883  0.921863  0.702137
2  0.233943  1.074849  0.143718

In [36]:
#column wise sum
dataframe.sum()

One      0.115363
Two     -1.182275
Three    0.165327
dtype: float64

In [37]:
# row wise sum
dataframe.sum(axis=1)

0    1.127098
1   -0.863608
2   -1.165074
dtype: float64

In [38]:
#get cumulitive sum

dataframe.cumsum()

One       Two     Three
0  0.993189  0.814437 -0.680529
1  0.349307 -0.107426  0.021609
2  0.115363 -1.182275  0.165327

### Array Manipulation

In [48]:
a = np.array([[1,2,4]])
b = np.array([[2,2,4]])
print(np.concatenate((a,b),axis=1)) #concatenating two arrays with same dimensions
print(np.vstack((a,b)))             # stacking array row wise
print(np.hstack((a,b)))             # stacking array column wise
print(np.column_stack((a,b)) )      # combining column wise stacked array

[[1 2 4 2 2 4]]
[[1 2 4]
 [2 2 4]]
[[1 2 4 2 2 4]]
[[1 2 4 2 2 4]]


#### creating dataframe from a series

In [50]:
df = pd.DataFrame(series_2)

In [51]:
df

0
A  22
B  45
C  39
D  88

#### creating a dataframe from numpy array

In [54]:
data1 = np.array([["a","b"],[6,12]])
data1

array([['a', 'b'],
       ['6', '12']], dtype='<U2')

In [56]:
df1 = pd.DataFrame({
    "A": data1[:,0],
    "B":data1[:,1]
})

In [57]:
df1

A   B
0  a   b
1  6  12